### ISSUE TITLE
Class 'CILogViewer\CILogViewer' not found with CI 3.X version

### ISSUE THREAD

**Issue by babulal107** [SeunMatt/codeigniter-log-viewer#11]
I am getting below error. I have load URL helper and also call parent constructor.

An uncaught Exception was encountered
Type: Error

Message: Class 'CILogViewer\CILogViewer' not found

Filename: /var/www/html/application/controllers/LogViewerController.php

Line Number: 12

Backtrace:

File: /var/www/html/index.php
Line: 315
Function: require_once

Here is my controller : 

class LogViewerController extends CI_Controller
{
    private $logViewer;

    public function __construct()
    {
        parent::__construct();
        $this->load->helper('url');
        $this->logViewer = new \CILogViewer\CILogViewer();

    }

    public function index()
    {
        echo $this->logViewer->showLogs();
        return;
    }

    public function test() {
        log_message('error', 'Error');
        echo 'test ok';
        return;
    }
}

**Comment by SeunMatt** [comment]
Hello @babulal107 
After adding the dependency in composer.json did you run `composer update`? If not, I'll recommend you do it.

- make sure your `composer.json` has this entry `"seunmatt/codeigniter-log-viewer": "1.1.1"`
- run `compser update`
- run `composer dump-autoload`
- make sure the `seunmatt/codeigniter-log-viewer` folder exists in your `vendor` folder.

Cheers.
