### ISSUE TITLE
cant access previous log files

### ISSUE THREAD

**Issue by munkiepus** [SeunMatt/codeigniter-log-viewer#17]
Hi 

I was having a problem where I couldn't access the previous log files, it turned out that it was because 
I had both these settings as false in the config

```
$config['allow_get_array'] = FALSE;
$config['enable_query_strings'] = FALSE;
```

there are security considerations to switching these to true, and it's not required at all for the rest of the app so seems silly to turn it on just for this one function.

Is there any other way of accessing the previous log files without having to turn these on?

Thnaks

**Comment by SeunMatt** [comment]
The other alternative would have been that we should use a path variable but that'll now require us to ask our users to be adding more paths in their route definition, which can be too much. 

The feasible alternative will be for you to fork the repo, make the update and use your own implementation.

I'm curious though as to why none of your paths are requiring query parameters. Are you running a CLI app? No data pagination?
