### ISSUE TITLE
Trying to get property 'config' of non-object

### ISSUE THREAD

**Issue by saurabhsharma2u** [SeunMatt/codeigniter-log-viewer#19]
i followed all the instructions, still getting error
`Severity: Notice

Message: Trying to get property 'config' of non-object

Filename: src/CILogViewer.php

Line Number: 102

Backtrace:

File: C:\xampp\htdocs\access\vendor\seunmatt\codeigniter-log-viewer\src\CILogViewer.php
`

`Type: Error

Message: Call to a member function item() on null

Filename: C:\xampp\htdocs\access\vendor\seunmatt\codeigniter-log-viewer\src\CILogViewer`

**Comment by SeunMatt** [comment]
- What CI version are you using?
- We recently released version 2 targetted at CI4. Please can you check that out and let me know if this is still an issue
