### ISSUE TITLE
Remove the Extra slash from LOG_VIEW_FILE_FOLDER Constants

### ISSUE THREAD

**Issue by rashidtab** [SeunMatt/codeigniter-log-viewer#2]
Now it is 
`const LOG_VIEW_FILE_FOLDER = APPPATH . "/views/cilogviewer";`

Change to 

`const LOG_VIEW_FILE_FOLDER = APPPATH . "views/cilogviewer";`

So that Double slash wont be appended. 

Environment Ubuntu, Php 7, Codeigniter 3

**Comment by SeunMatt** [comment]
@rashidtab 

Thanks for this precious observation. It has been addressed in the latest updates and will be part of the next release
