### ISSUE TITLE
Extended log levels 

### ISSUE THREAD

**Issue by awalls** [SeunMatt/codeigniter-log-viewer#20]
Hi, just curious to see if there are any plans to enable the log parser to deal with custom log levels. We have extended CI_Log to include our own custom log level but the current implementation of this only supports the native CI log levels.

**Comment by SeunMatt** [comment]
Hello @awalls 
I can't promise anything but it's  an interesting topic I'm willing to explore in the nearest future.

**Comment by awalls** [comment]
No worries. Fully understand.
