### ISSUE TITLE
Need a Feature to change Log Folder path or get from Codeigniter Log path

### ISSUE THREAD

**Issue by rashidtab** [SeunMatt/codeigniter-log-viewer#3]
We use centralized logging directory.
usually Logs are written in `/var/log/localhost/....`

We define this path in codeigniter `config.php` file
`$config['log_path'] = "/var/log/localhost"`

Is there any way we can fetch or pass this path information as `const LOG_FOLDER_PREFIX = "/logs";`

**Comment by rashidtab** [comment]
I am achieving this using following Hack

In My controller
```
        require_once FCPATH.'vendor/autoload.php';
        $CILogs = new \CILogViewer\CILogViewer($this->config->item('log_path'));
        echo $CILogs->showLogs();
```

In CILogViewer.php file inside composer vendor directory

```
private $LOG_FOLDER_PREFIX = '';

    public function __construct($path=NULL) {
        if($path){
            $this->LOG_FOLDER_PREFIX = $path;
        }
        $this->init();
    }


```

**Comment by SeunMatt** [comment]
Hello @rashidtab
 
Thanks for this observation, it has been added as part of the master branch and will be part of 1.1.0 release.
