### ISSUE TITLE
localhost is currently unable to handle this request. HTTP ERROR 500

### ISSUE THREAD

**Issue by akshilshah** [SeunMatt/codeigniter-log-viewer#5]
Hi,
While loading the controller I get an error of HTTP ERROR 500. 
I followed the exact steps but still can't figure out what can be done.
I would really appreciate the help thank you

**Comment by SeunMatt** [comment]
Hello @akshilshah 

You'll need to provide more information about what your setup.

1. **Copy-paste the full stack trace, you should find that in the logs folder**
2. What version of CI are you using?
3. Copy-paste just the function that you mapped to the controller for displaying logs.
4. Possibly paste the route config as well.

Cheers
