### ISSUE TITLE
Unexpected "const" in 67 line

### ISSUE THREAD

**Issue by chileung69** [SeunMatt/codeigniter-log-viewer#7]
When log the library of CILogViewer.php, PHP has error on unepxeted "const" in 67 line. I found out solution is remove private. And we need also remove the following line private. Hope can commit a fix on that issue. Thank you so much. And your plugin is very helpful.

**Comment by SeunMatt** [comment]
Hi @chileung69 

What version of PHP are you using as at the time you got the reported error?

**Comment by chileung69** [comment]
Hi @SeunMatt PHP 7.0.33

**Comment by truelineinfotech** [comment]
@chileung69 can you share screenshot ? if possible.

**Comment by karthikc386** [comment]
Even I have the same issue.
My php version is 

PHP 7.0.32-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.32-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies


![localhost demoserver index php logs](https://user-images.githubusercontent.com/7878694/52186103-44984980-284b-11e9-9750-2372bda85066.png)

**Comment by truelineinfotech** [comment]
you can use define() instead
[define()](http://php.net/manual/en/function.define.php)
