### ISSUE TITLE
I found LFI on this Libary

### ISSUE THREAD

**Issue by alifbint** [SeunMatt/codeigniter-log-viewer#8]
Hello, I found a security bug severity level high in this library. I use feature download log in this library to download my config file it's work I just decode **../config/database.php** to base64 then I paste to the url like this **URL?dl=Li4vLi4vaW5kZXgucGhw** when I access it I can download my database.php config

**Comment by SeunMatt** [comment]
Hi @alifbint 

Thanks for the discovery 👏. The bug has been fixed with a new release v1.1.1

Please if you have any other findings, don't hesitate to report.

Cheers

**Comment by alifbint** [comment]
Sure, I will report if I find another bug
thanks
