### ISSUE TITLE
Issue with initiating the CodeIgniter instance 

### ISSUE THREAD

**Issue by karthikc386** [SeunMatt/codeigniter-log-viewer#9]
It's the first time I am initiating the CodeIgniter instance in the vendor file

$this->CI = &get_instance();
It return null for me.

![image123](https://user-images.githubusercontent.com/7878694/52895851-179e4c00-31e6-11e9-92ef-db546e8e247a.png)

Let me know what I am missing here.

**Comment by SeunMatt** [comment]
Hi @karthikc386 
I'm sorry for the late response. Please try the following:
1. Run `composer dump-autoload`
2. Try initiating the CI instance from within your code first e.g. in any of your controllers add this line
`$this->CI = &get_instance();` then assert that `$this->CI` is not null by using the `is_null()` function.

Cheers.

**Comment by ArmandArthur** [comment]
I have the same error ! What's wrong?

**Comment by ArmandArthur** [comment]
I forget : parent::__construct(); in my controller.

**Comment by SeunMatt** [comment]
Good thing you were able to figure it out @ArmandArthur 

Hope others will learn from your comments

**Comment by karthikc386** [comment]
Thanks. I had the same issue @ArmandArthur.
